# Generated by Django 2.2.6 on 2020-02-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KidServices',
        ),
        migrations.DeleteModel(
            name='MenServices',
        ),
        migrations.DeleteModel(
            name='OtherServices',
        ),
    ]
