# Generated by Django 2.2.6 on 2020-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0009_auto_20200221_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoimage',
            name='barbershop',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
