# Generated by Django 2.2.6 on 2020-03-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0010_logoimage_barbershop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoimage',
            name='barbershop',
        ),
    ]
