# Generated by Django 2.2.6 on 2020-03-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0012_auto_20200326_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbers',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
