# Generated by Django 2.2.6 on 2020-04-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200218_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menservices',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
