# Generated by Django 2.2.6 on 2020-04-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200422_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidservices',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menservices',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otherservices',
            name='price',
            field=models.IntegerField(),
        ),
    ]
