# Generated by Django 2.2.6 on 2020-04-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200422_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidservices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menservices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='otherservices',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
