# Generated by Django 2.2.6 on 2020-02-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_completedclients_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedclients',
            name='user',
        ),
    ]
