# Generated by Django 2.2.6 on 2020-03-26 20:55

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0011_remove_logoimage_barbershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbers',
            name='file',
            field=models.ImageField(blank=True, upload_to='barber_profile_img/'),
        ),
        migrations.AddField(
            model_name='barbers',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
