# Generated by Django 2.2.6 on 2020-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0014_barbers_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbers',
            name='license_num',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
