# Generated by Django 2.2.6 on 2020-03-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0015_barbers_license_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedclients',
            name='completed_by',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
