# Generated by Django 2.2.6 on 2020-03-30 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0016_completedclients_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedclients',
            name='completed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='barbershop.Barbers'),
        ),
    ]
