# Generated by Django 2.2.6 on 2020-03-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0017_auto_20200329_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbers',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10),
        ),
    ]
