# Generated by Django 2.2.6 on 2020-03-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0018_auto_20200330_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbers',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
