# Generated by Django 2.2.6 on 2020-04-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0023_client_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_completed',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
