# Generated by Django 2.2.6 on 2020-04-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0024_client_date_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedClients',
        ),
    ]
