# Generated by Django 2.2.6 on 2020-04-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0025_delete_completedclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Waiting'), ('SERV', 'Serving'), ('CMPL', 'Completed')], default='WAIT', max_length=2),
        ),
    ]
