# Generated by Django 2.2.6 on 2020-04-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0026_client_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logoimage',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Serving', 'Serving'), ('Completed', 'Completed')], default='Waiting', max_length=10),
        ),
    ]
