# Generated by Django 2.2.6 on 2020-04-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0027_auto_20200418_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='completed',
        ),
    ]
