# Generated by Django 2.2.6 on 2020-04-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0028_remove_client_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
