# Generated by Django 2.2.6 on 2020-05-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0029_client_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='completed_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
