# Generated by Django 2.2.6 on 2020-05-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photocrop', '0013_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
